/* Generated from lexical-tokens.json by npm run generate. */

#ifndef TREE_SITTER_SH_LEXICAL_TOKENS_H_
#define TREE_SITTER_SH_LEXICAL_TOKENS_H_

#define SH_LEXICAL_SOURCE_TOKENS(X) \
  X(FILE_DESCRIPTOR, IO_NUMBER_BEGIN_PIECE) \
  X(PIPELINE_NEGATION, BANG_BEGIN_PIECE) \
  X(IF_KEYWORD, IF_KEYWORD_BEGIN_PIECE) \
  X(THEN_KEYWORD, THEN_KEYWORD_BEGIN_PIECE) \
  X(ELIF_KEYWORD, ELIF_KEYWORD_BEGIN_PIECE) \
  X(ELSE_KEYWORD, ELSE_KEYWORD_BEGIN_PIECE) \
  X(FI_KEYWORD, FI_KEYWORD_BEGIN_PIECE) \
  X(FOR_KEYWORD, FOR_KEYWORD_BEGIN_PIECE) \
  X(IN_KEYWORD, IN_KEYWORD_BEGIN_PIECE) \
  X(DO_KEYWORD, DO_KEYWORD_BEGIN_PIECE) \
  X(DONE_KEYWORD, DONE_KEYWORD_BEGIN_PIECE) \
  X(CASE_KEYWORD, CASE_KEYWORD_BEGIN_PIECE) \
  X(ESAC_KEYWORD, ESAC_KEYWORD_BEGIN_PIECE) \
  X(WHILE_KEYWORD, WHILE_KEYWORD_BEGIN_PIECE) \
  X(UNTIL_KEYWORD, UNTIL_KEYWORD_BEGIN_PIECE) \
  X(HERE_DOCUMENT_LINE_END, HERE_DOCUMENT_LINE_END_BEGIN_PIECE) \
  X(QUOTED_HERE_DOCUMENT_END_TEXT, QUOTED_HERE_DOCUMENT_END_TEXT_BEGIN_PIECE) \
  X(QUOTED_HERE_DOCUMENT_TEXT, QUOTED_HERE_DOCUMENT_TEXT_BEGIN_PIECE) \
  X(HERE_DOCUMENT_END_LEADING_TABS, HERE_DOCUMENT_END_LEADING_TABS_BEGIN_PIECE) \
  X(NEWLINE, NEWLINE_BEGIN_PIECE) \
  X(COMMENT_START, COMMENT_TEXT_BEGIN_PIECE) \
  X(BRACED_POSITIONAL_PARAMETER_START, BRACED_POSITIONAL_PARAMETER_BEGIN_PIECE) \
  X(PATTERN_BRACKET_CHARACTER, PATTERN_BRACKET_CHARACTER_BEGIN_PIECE) \
  X(PARAMETER_PATTERN_BRACKET_CHARACTER, PARAMETER_PATTERN_BRACKET_CHARACTER_BEGIN_PIECE) \
  X(PATTERN_BRACKET_HYPHEN, PATTERN_BRACKET_HYPHEN_BEGIN_PIECE) \
  X(ASSIGNMENT_NAME_TOKEN, ASSIGNMENT_NAME_BEGIN_PIECE) \
  X(FNAME_TOKEN, FNAME_BEGIN_PIECE) \
  X(PRE_NEWLINE_BLANK, PRE_NEWLINE_BLANK_BEGIN_PIECE) \
  X(DOLLAR_SINGLE_QUOTE_ESCAPE, DOLLAR_SINGLE_QUOTE_ESCAPE_BEGIN_PIECE) \
  X(LITERAL_BEGIN, LITERAL_BEGIN_PIECE) \
  X(ASSIGNMENT_LITERAL_BEGIN, ASSIGNMENT_LITERAL_BEGIN_PIECE) \
  X(PARAMETER_LITERAL_BEGIN, PARAMETER_LITERAL_BEGIN_PIECE) \
  X(NAME_BEGIN, NAME_BEGIN_PIECE) \
  X(VARIABLE_NAME_BEGIN, VARIABLE_NAME_BEGIN_PIECE) \
  X(ESCAPED_CHARACTER_BEGIN, ESCAPED_CHARACTER_BEGIN_PIECE) \
  X(SINGLE_QUOTE_CONTENT_BEGIN, SINGLE_QUOTE_CONTENT_BEGIN_PIECE) \
  X(DOUBLE_QUOTE_TEXT_BEGIN, DOUBLE_QUOTE_TEXT_BEGIN_PIECE) \
  X(DOUBLE_QUOTE_ESCAPE_BEGIN, DOUBLE_QUOTE_ESCAPE_BEGIN_PIECE) \
  X(DOLLAR_SINGLE_QUOTE_TEXT_BEGIN, DOLLAR_SINGLE_QUOTE_TEXT_BEGIN_PIECE) \
  X(DOUBLE_QUOTED_PARAMETER_TEXT_BEGIN, DOUBLE_QUOTED_PARAMETER_TEXT_BEGIN_PIECE) \
  X(DOUBLE_QUOTED_PARAMETER_ESCAPE_BEGIN, DOUBLE_QUOTED_PARAMETER_ESCAPE_BEGIN_PIECE) \
  X(HERE_DOCUMENT_TEXT_BEGIN, HERE_DOCUMENT_TEXT_BEGIN_PIECE) \
  X(HERE_DOCUMENT_ESCAPE_BEGIN, HERE_DOCUMENT_ESCAPE_BEGIN_PIECE) \
  X(HERE_DOCUMENT_END_TEXT_BEGIN, HERE_DOCUMENT_END_TEXT_BEGIN_PIECE) \
  X(UNBRACED_POSITIONAL_PARAMETER_BEGIN, UNBRACED_POSITIONAL_PARAMETER_BEGIN_PIECE) \
  X(SPECIAL_PARAMETER_BEGIN, SPECIAL_PARAMETER_BEGIN_PIECE) \
  X(SPECIAL_PARAMETER_HASH_BEGIN, SPECIAL_PARAMETER_HASH_BEGIN_PIECE) \
  X(PARAMETER_VALUE_OPERATOR_BEGIN, PARAMETER_VALUE_OPERATOR_BEGIN_PIECE) \
  X(PARAMETER_PATTERN_OPERATOR_BEGIN, PARAMETER_PATTERN_OPERATOR_BEGIN_PIECE) \
  X(ARITHMETIC_NUMBER_BEGIN, ARITHMETIC_NUMBER_BEGIN_PIECE) \
  X(ARITHMETIC_VARIABLE_BEGIN, ARITHMETIC_VARIABLE_BEGIN_PIECE) \
  X(ARITHMETIC_UNARY_OPERATOR_BEGIN, ARITHMETIC_UNARY_OPERATOR_BEGIN_PIECE) \
  X(ARITHMETIC_ASSIGNMENT_OPERATOR_BEGIN, ARITHMETIC_ASSIGNMENT_OPERATOR_BEGIN_PIECE) \
  X(ARITHMETIC_QUESTION_OPERATOR_BEGIN, ARITHMETIC_QUESTION_OPERATOR_BEGIN_PIECE) \
  X(ARITHMETIC_COLON_OPERATOR_BEGIN, ARITHMETIC_COLON_OPERATOR_BEGIN_PIECE) \
  X(ARITHMETIC_LOGICAL_OR_OPERATOR_BEGIN, ARITHMETIC_LOGICAL_OR_OPERATOR_BEGIN_PIECE) \
  X(ARITHMETIC_LOGICAL_AND_OPERATOR_BEGIN, ARITHMETIC_LOGICAL_AND_OPERATOR_BEGIN_PIECE) \
  X(ARITHMETIC_BITWISE_OR_OPERATOR_BEGIN, ARITHMETIC_BITWISE_OR_OPERATOR_BEGIN_PIECE) \
  X(ARITHMETIC_BITWISE_XOR_OPERATOR_BEGIN, ARITHMETIC_BITWISE_XOR_OPERATOR_BEGIN_PIECE) \
  X(ARITHMETIC_BITWISE_AND_OPERATOR_BEGIN, ARITHMETIC_BITWISE_AND_OPERATOR_BEGIN_PIECE) \
  X(ARITHMETIC_EQUALITY_OPERATOR_BEGIN, ARITHMETIC_EQUALITY_OPERATOR_BEGIN_PIECE) \
  X(ARITHMETIC_RELATIONAL_OPERATOR_BEGIN, ARITHMETIC_RELATIONAL_OPERATOR_BEGIN_PIECE) \
  X(ARITHMETIC_SHIFT_OPERATOR_BEGIN, ARITHMETIC_SHIFT_OPERATOR_BEGIN_PIECE) \
  X(ARITHMETIC_ADDITIVE_OPERATOR_BEGIN, ARITHMETIC_ADDITIVE_OPERATOR_BEGIN_PIECE) \
  X(ARITHMETIC_MULTIPLICATIVE_OPERATOR_BEGIN, ARITHMETIC_MULTIPLICATIVE_OPERATOR_BEGIN_PIECE) \
  X(AND_IF_BEGIN, AND_IF_BEGIN_PIECE) \
  X(OR_IF_BEGIN, OR_IF_BEGIN_PIECE) \
  X(DSEMI_BEGIN, DSEMI_BEGIN_PIECE) \
  X(SEMI_AND_BEGIN, SEMI_AND_BEGIN_PIECE) \
  X(LESSAND_BEGIN, LESSAND_BEGIN_PIECE) \
  X(GREATAND_BEGIN, GREATAND_BEGIN_PIECE) \
  X(DGREAT_BEGIN, DGREAT_BEGIN_PIECE) \
  X(LESSGREAT_BEGIN, LESSGREAT_BEGIN_PIECE) \
  X(CLOBBER_BEGIN, CLOBBER_BEGIN_PIECE) \
  X(DLESS_OPERATOR_BEGIN, DLESS_OPERATOR_BEGIN_PIECE) \
  X(DLESSDASH_OPERATOR_BEGIN, DLESSDASH_OPERATOR_BEGIN_PIECE) \
  X(PATTERN_STAR_BEGIN, PATTERN_STAR_BEGIN_PIECE) \
  X(PATTERN_QUESTION_BEGIN, PATTERN_QUESTION_BEGIN_PIECE) \
  X(PATTERN_NEGATION_BEGIN, PATTERN_NEGATION_BEGIN_PIECE) \
  X(PATTERN_CLASS_CONTENT_BEGIN, PATTERN_CLASS_CONTENT_BEGIN_PIECE) \
  X(PARAMETER_PATTERN_CLASS_CONTENT_BEGIN, PARAMETER_PATTERN_CLASS_CONTENT_BEGIN_PIECE) \
  X(PATTERN_COLLATING_CHARACTER_BEGIN, PATTERN_COLLATING_CHARACTER_BEGIN_PIECE) \
  X(PARAMETER_PATTERN_COLLATING_CHARACTER_BEGIN, PARAMETER_PATTERN_COLLATING_CHARACTER_BEGIN_PIECE) \
  X(PATTERN_EQUIVALENCE_CHARACTER_BEGIN, PATTERN_EQUIVALENCE_CHARACTER_BEGIN_PIECE) \
  X(PARAMETER_PATTERN_EQUIVALENCE_CHARACTER_BEGIN, PARAMETER_PATTERN_EQUIVALENCE_CHARACTER_BEGIN_PIECE) \
  X(LOGICAL_BLANK_BEGIN, LOGICAL_BLANK_BEGIN_PIECE) \
  X(PATTERN_INITIAL_RIGHT_BRACKET_BEGIN, PATTERN_INITIAL_RIGHT_BRACKET_BEGIN_PIECE) \
  X(HERE_DOCUMENT_END_LINE_END, HERE_DOCUMENT_END_LINE_END_BEGIN_PIECE) \
  X(WORD_FALLBACK_LITERAL_BEGIN, WORD_FALLBACK_LITERAL_BEGIN_PIECE) \
  X(ASSIGNMENT_FALLBACK_LITERAL_BEGIN, ASSIGNMENT_FALLBACK_LITERAL_BEGIN_PIECE) \
  X(PARAMETER_FALLBACK_LITERAL_BEGIN, PARAMETER_FALLBACK_LITERAL_BEGIN_PIECE) \
  X(WORD_FALLBACK_CHARACTER_BEGIN, WORD_FALLBACK_CHARACTER_BEGIN_PIECE) \
  X(ASSIGNMENT_FALLBACK_CHARACTER_BEGIN, ASSIGNMENT_FALLBACK_CHARACTER_BEGIN_PIECE) \
  X(PARAMETER_FALLBACK_CHARACTER_BEGIN, PARAMETER_FALLBACK_CHARACTER_BEGIN_PIECE) \
  X(WORD_INITIAL_LITERAL_BEGIN, WORD_INITIAL_LITERAL_BEGIN_PIECE) \
  X(WORD_INITIAL_FALLBACK_LITERAL_BEGIN, WORD_INITIAL_FALLBACK_LITERAL_BEGIN_PIECE) \
  X(WORD_INITIAL_PATTERN_STAR_BEGIN, WORD_INITIAL_PATTERN_STAR_BEGIN_PIECE) \
  X(WORD_INITIAL_PATTERN_QUESTION_BEGIN, WORD_INITIAL_PATTERN_QUESTION_BEGIN_PIECE) \
  X(WORD_INITIAL_ESCAPED_CHARACTER_BEGIN, WORD_INITIAL_ESCAPED_CHARACTER_BEGIN_PIECE) \
  X(PARAMETER_HYPHEN_BEGIN, PARAMETER_HYPHEN_BEGIN_PIECE) \
  X(PARAMETER_QUESTION_BEGIN, PARAMETER_QUESTION_BEGIN_PIECE) \
  X(ARITHMETIC_BLANK_BEGIN, ARITHMETIC_BLANK_BEGIN_PIECE)

#define SH_PHYSICAL_SOURCE_TOKENS(X) \
  X(LEFT_BRACE, LEFT_BRACE_PREFIX, LEFT_BRACE_CHARACTER) \
  X(RIGHT_BRACE, RIGHT_BRACE_PREFIX, RIGHT_BRACE_CHARACTER) \
  X(PATTERN_SPECIAL_LEFT_BRACKET, PATTERN_SPECIAL_LEFT_BRACKET_PREFIX, PATTERN_SPECIAL_LEFT_BRACKET_CHARACTER) \
  X(COMMENT_LINE_END, COMMENT_LINE_END_BEGIN_PREFIX, COMMENT_LINE_END_BEGIN_CHARACTER) \
  X(DOLLAR_EXPANSION_START, DOLLAR_EXPANSION_START_PREFIX, DOLLAR_EXPANSION_START_CHARACTER) \
  X(BACKQUOTE_START, BACKQUOTE_START_PREFIX, BACKQUOTE_START_CHARACTER) \
  X(BACKQUOTE_END, BACKQUOTE_END_PREFIX, BACKQUOTE_END_CHARACTER) \
  X(WORD_PATTERN_BRACKET_OPEN, WORD_PATTERN_BRACKET_OPEN_PREFIX, WORD_PATTERN_BRACKET_OPEN_CHARACTER) \
  X(PARAMETER_PATTERN_BRACKET_OPEN, PARAMETER_PATTERN_BRACKET_OPEN_PREFIX, PARAMETER_PATTERN_BRACKET_OPEN_CHARACTER) \
  X(DOUBLE_QUOTED_BACKQUOTE_START, DOUBLE_QUOTED_BACKQUOTE_START_PREFIX, DOUBLE_QUOTED_BACKQUOTE_START_CHARACTER) \
  X(PATTERN_CHARACTER_CLASS_END_COLON, PATTERN_CHARACTER_CLASS_END_COLON_PREFIX, PATTERN_CHARACTER_CLASS_END_COLON_CHARACTER) \
  X(PUNCT_LEFT_PARENTHESIS, PUNCT_LEFT_PARENTHESIS_PREFIX, PUNCT_LEFT_PARENTHESIS_CHARACTER) \
  X(PUNCT_RIGHT_PARENTHESIS, PUNCT_RIGHT_PARENTHESIS_PREFIX, PUNCT_RIGHT_PARENTHESIS_CHARACTER) \
  X(PUNCT_SEMICOLON, PUNCT_SEMICOLON_PREFIX, PUNCT_SEMICOLON_CHARACTER) \
  X(PUNCT_AMPERSAND, PUNCT_AMPERSAND_PREFIX, PUNCT_AMPERSAND_CHARACTER) \
  X(PUNCT_PIPE, PUNCT_PIPE_PREFIX, PUNCT_PIPE_CHARACTER) \
  X(PUNCT_LESS, PUNCT_LESS_PREFIX, PUNCT_LESS_CHARACTER) \
  X(PUNCT_GREATER, PUNCT_GREATER_PREFIX, PUNCT_GREATER_CHARACTER) \
  X(PUNCT_EQUALS, PUNCT_EQUALS_PREFIX, PUNCT_EQUALS_CHARACTER) \
  X(PUNCT_RIGHT_BRACKET, PUNCT_RIGHT_BRACKET_PREFIX, PUNCT_RIGHT_BRACKET_CHARACTER) \
  X(PUNCT_COLON, PUNCT_COLON_PREFIX, PUNCT_COLON_CHARACTER) \
  X(PUNCT_DOT, PUNCT_DOT_PREFIX, PUNCT_DOT_CHARACTER) \
  X(SQ_OPEN, SQ_OPEN_PREFIX, SQ_OPEN_CHARACTER) \
  X(SQ_CLOSE, SQ_CLOSE_PREFIX, SQ_CLOSE_CHARACTER) \
  X(DQ_OPEN, DQ_OPEN_PREFIX, DQ_OPEN_CHARACTER) \
  X(DQ_CLOSE, DQ_CLOSE_PREFIX, DQ_CLOSE_CHARACTER) \
  X(DOLLAR_SQ_DOLLAR, DOLLAR_SQ_DOLLAR_PREFIX, DOLLAR_SQ_DOLLAR_CHARACTER) \
  X(DOLLAR_SQ_OPEN, DOLLAR_SQ_OPEN_PREFIX, DOLLAR_SQ_OPEN_CHARACTER) \
  X(DOLLAR_SQ_CLOSE, DOLLAR_SQ_CLOSE_PREFIX, DOLLAR_SQ_CLOSE_CHARACTER) \
  X(PARAMETER_OPEN, PARAMETER_OPEN_PREFIX, PARAMETER_OPEN_CHARACTER) \
  X(PARAMETER_CLOSE, PARAMETER_CLOSE_PREFIX, PARAMETER_CLOSE_CHARACTER) \
  X(COMMAND_OPEN, COMMAND_OPEN_PREFIX, COMMAND_OPEN_CHARACTER) \
  X(NUMERIC_PARAMETER_DIGIT, NUMERIC_PARAMETER_DIGIT_PREFIX, NUMERIC_PARAMETER_DIGIT_CHARACTER) \
  X(WORD_TILDE_START, WORD_TILDE_START_PREFIX, WORD_TILDE_START_CHARACTER) \
  X(ASSIGNMENT_TILDE_START, ASSIGNMENT_TILDE_START_PREFIX, ASSIGNMENT_TILDE_START_CHARACTER) \
  X(PARAMETER_TILDE_START, PARAMETER_TILDE_START_PREFIX, PARAMETER_TILDE_START_CHARACTER) \
  X(LOGICAL_NEWLINE_BEGIN, LOGICAL_NEWLINE_BEGIN_PREFIX, LOGICAL_NEWLINE_BEGIN_CHARACTER) \
  X(FALLBACK_BRACKET_OPEN, FALLBACK_BRACKET_OPEN_PREFIX, FALLBACK_BRACKET_OPEN_CHARACTER) \
  X(FALLBACK_BRACKET_CLOSE, FALLBACK_BRACKET_CLOSE_PREFIX, FALLBACK_BRACKET_CLOSE_CHARACTER) \
  X(FALLBACK_COLON, FALLBACK_COLON_PREFIX, FALLBACK_COLON_CHARACTER) \
  X(FALLBACK_DOT, FALLBACK_DOT_PREFIX, FALLBACK_DOT_CHARACTER) \
  X(FALLBACK_EQUALS, FALLBACK_EQUALS_PREFIX, FALLBACK_EQUALS_CHARACTER) \
  X(WORD_INITIAL_PATTERN_BRACKET_OPEN, WORD_INITIAL_PATTERN_BRACKET_OPEN_PREFIX, WORD_INITIAL_PATTERN_BRACKET_OPEN_CHARACTER) \
  X(WORD_INITIAL_SQ_OPEN, WORD_INITIAL_SQ_OPEN_PREFIX, WORD_INITIAL_SQ_OPEN_CHARACTER) \
  X(WORD_INITIAL_DQ_OPEN, WORD_INITIAL_DQ_OPEN_PREFIX, WORD_INITIAL_DQ_OPEN_CHARACTER) \
  X(WORD_INITIAL_DOLLAR_SQ_DOLLAR, WORD_INITIAL_DOLLAR_SQ_DOLLAR_PREFIX, WORD_INITIAL_DOLLAR_SQ_DOLLAR_CHARACTER) \
  X(WORD_INITIAL_DOLLAR_EXPANSION_START, WORD_INITIAL_DOLLAR_EXPANSION_START_PREFIX, WORD_INITIAL_DOLLAR_EXPANSION_START_CHARACTER) \
  X(WORD_INITIAL_BACKQUOTE_START, WORD_INITIAL_BACKQUOTE_START_PREFIX, WORD_INITIAL_BACKQUOTE_START_CHARACTER) \
  X(FALLBACK_SPECIAL_BRACKET_OPEN, FALLBACK_SPECIAL_BRACKET_OPEN_PREFIX, FALLBACK_SPECIAL_BRACKET_OPEN_CHARACTER)

#define SH_WHOLE_SOURCE_TOKENS(X) \
  X(IF_KEYWORD, IF_KEYWORD_BEGIN_WHOLE) \
  X(THEN_KEYWORD, THEN_KEYWORD_BEGIN_WHOLE) \
  X(ELIF_KEYWORD, ELIF_KEYWORD_BEGIN_WHOLE) \
  X(ELSE_KEYWORD, ELSE_KEYWORD_BEGIN_WHOLE) \
  X(FI_KEYWORD, FI_KEYWORD_BEGIN_WHOLE) \
  X(FOR_KEYWORD, FOR_KEYWORD_BEGIN_WHOLE) \
  X(IN_KEYWORD, IN_KEYWORD_BEGIN_WHOLE) \
  X(DO_KEYWORD, DO_KEYWORD_BEGIN_WHOLE) \
  X(DONE_KEYWORD, DONE_KEYWORD_BEGIN_WHOLE) \
  X(CASE_KEYWORD, CASE_KEYWORD_BEGIN_WHOLE) \
  X(ESAC_KEYWORD, ESAC_KEYWORD_BEGIN_WHOLE) \
  X(WHILE_KEYWORD, WHILE_KEYWORD_BEGIN_WHOLE) \
  X(UNTIL_KEYWORD, UNTIL_KEYWORD_BEGIN_WHOLE) \
  X(PARAMETER_VALUE_OPERATOR_BEGIN, PARAMETER_VALUE_OPERATOR_BEGIN_WHOLE) \
  X(PARAMETER_PATTERN_OPERATOR_BEGIN, PARAMETER_PATTERN_OPERATOR_BEGIN_WHOLE) \
  X(WORD_INITIAL_LITERAL_BEGIN, WORD_INITIAL_LITERAL_BEGIN_WHOLE)

#endif
